import { format } from 'date-fns'

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

interface PaymentRow {
  memberName: string
  memberNumber: number
  plan: string
  amount: number
  admission_fee: number
  payment_mode: string
}

interface DailyReportData {
  gymName: string
  date: string
  payments: PaymentRow[]
}

export function generateDailyCollectionPDF(data: DailyReportData) {
  const { gymName, date, payments } = data
  const totalCash = payments.filter(p => p.payment_mode === 'cash').reduce((s, p) => s + p.amount + p.admission_fee, 0)
  const totalUPI  = payments.filter(p => p.payment_mode === 'upi').reduce((s, p) => s + p.amount + p.admission_fee, 0)
  const totalCard = payments.filter(p => p.payment_mode === 'card').reduce((s, p) => s + p.amount + p.admission_fee, 0)
  const grandTotal = totalCash + totalUPI + totalCard

  const fmt = (n: number) => `Rs.${n.toLocaleString('en-IN')}`
  const displayDate = format(new Date(date), 'dd MMMM yyyy')

  const rows = payments.map(p => `
    <tr>
      <td>#${p.memberNumber}</td>
      <td>${escapeHtml(p.memberName)}</td>
      <td style="text-transform:capitalize">${p.plan}</td>
      <td>${p.payment_mode.toUpperCase()}</td>
      <td style="text-align:right">${fmt(p.amount)}</td>
      <td style="text-align:right">${p.admission_fee > 0 ? fmt(p.admission_fee) : '—'}</td>
      <td style="text-align:right;font-weight:600">${fmt(p.amount + p.admission_fee)}</td>
    </tr>
  `).join('')

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>Daily Collection - ${displayDate}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 13px; color: #111; padding: 32px; }
        .header { text-align: center; margin-bottom: 24px; }
        .header h1 { font-size: 22px; font-weight: 700; }
        .header p { color: #555; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th { background: #f3f4f6; text-align: left; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #555; border-bottom: 2px solid #e5e7eb; }
        td { padding: 8px 10px; border-bottom: 1px solid #f3f4f6; }
        tr:last-child td { border-bottom: none; }
        .summary { display: flex; gap: 16px; justify-content: flex-end; margin-top: 8px; }
        .summary-box { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 20px; text-align: center; min-width: 120px; }
        .summary-box .label { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: 0.05em; }
        .summary-box .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
        .total-box { background: #f97316; color: white; border-color: #f97316; }
        .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #aaa; }
        @media print { body { padding: 16px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escapeHtml(gymName)}</h1>
        <p>Daily Collection Report — ${displayDate}</p>
      </div>

      ${payments.length === 0
        ? '<p style="text-align:center;color:#888;padding:32px">No payments collected today.</p>'
        : `<table>
            <thead>
              <tr>
                <th>#</th>
                <th>Member</th>
                <th>Plan</th>
                <th>Mode</th>
                <th style="text-align:right">Membership</th>
                <th style="text-align:right">Admission</th>
                <th style="text-align:right">Total</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>`
      }

      <div class="summary">
        <div class="summary-box">
          <div class="label">Cash</div>
          <div class="value">${fmt(totalCash)}</div>
        </div>
        <div class="summary-box">
          <div class="label">UPI</div>
          <div class="value">${fmt(totalUPI)}</div>
        </div>
        <div class="summary-box">
          <div class="label">Card</div>
          <div class="value">${fmt(totalCard)}</div>
        </div>
        <div class="summary-box total-box">
          <div class="label">Grand Total</div>
          <div class="value">${fmt(grandTotal)}</div>
        </div>
      </div>

      <div class="footer">Generated by GymFlow · ${format(new Date(), 'dd MMM yyyy, hh:mm a')}</div>
    </body>
    </html>
  `

  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => { win.print() }, 500)
}
