/** alias_normalized → canonical display name */
export const ALIAS_MAP: Record<string, string> = {
  // Pondicherry / Puducherry
  'pondy':            'Puducherry',
  'pondicherry':      'Puducherry',
  'pudu':             'Puducherry',
  'puducherry':       'Puducherry',
  'pondycherry':      'Puducherry',

  // Tamil Nadu cities
  'trichy':           'Tiruchirappalli',
  'tiruchy':          'Tiruchirappalli',
  'trichinopoly':     'Tiruchirappalli',
  'tiruchirappalli':  'Tiruchirappalli',
  'thirchy':          'Tiruchirappalli',
  'madurai':          'Madurai',
  'coimbatore':       'Coimbatore',
  'cbe':              'Coimbatore',
  'kovai':            'Coimbatore',
  'salem':            'Salem',
  'erode':            'Erode',
  'tirunelveli':      'Tirunelveli',
  'tirunelvelly':     'Tirunelveli',
  'nellai':           'Tirunelveli',
  'vellore':          'Vellore',
  'thanjavur':        'Thanjavur',
  'tanjore':          'Thanjavur',
  'chengalpattu':     'Chengalpattu',
  'chengalpet':       'Chengalpattu',
  'kancheepuram':     'Kanchipuram',
  'kanchi':           'Kanchipuram',
  'kanchipuram':      'Kanchipuram',
  'villupuram':       'Villupuram',
  'villipuram':       'Villupuram',
  'vilupuram':        'Villupuram',
  'cuddalore':        'Cuddalore',
  'cudalore':         'Cuddalore',
  'kumbakonam':       'Kumbakonam',
  'kumbakonum':       'Kumbakonam',
  'nagapattinam':     'Nagapattinam',
  'nagapatinam':      'Nagapattinam',
  'dindigul':         'Dindigul',
  'dindugal':         'Dindigul',
  'tiruppur':         'Tiruppur',
  'tirupur':          'Tiruppur',
  'hosur':            'Hosur',
  'krishnagiri':      'Krishnagiri',
  'dharmapuri':       'Dharmapuri',
  'namakkal':         'Namakkal',
  'karur':            'Karur',
  'perambalur':       'Perambalur',
  'ariyalur':         'Ariyalur',
  'sivaganga':        'Sivaganga',
  'virudhunagar':     'Virudhunagar',
  'ramanathapuram':   'Ramanathapuram',
  'thoothukudi':      'Thoothukudi',
  'tuticorin':        'Thoothukudi',
  'kanyakumari':      'Kanyakumari',
  'nagercoil':        'Nagercoil',

  // Chennai localities
  'tnagar':           'T. Nagar',
  'tnagr':            'T. Nagar',
  'thyagarayanagar':  'T. Nagar',
  'mylapore':         'Mylapore',
  'velachery':        'Velachery',
  'velacherri':       'Velachery',
  'velacheri':        'Velachery',
  'adyar':            'Adyar',
  'annanagar':        'Anna Nagar',
  'annanagr':         'Anna Nagar',
  'chennai':          'Chennai',
  'madras':           'Chennai',
  'tambaram':         'Tambaram',
  'chrompet':         'Chromepet',
  'chromepet':        'Chromepet',
  'perambur':         'Perambur',
  'ambattur':         'Ambattur',
  'avadi':            'Avadi',
  'porur':            'Porur',
  'guindy':           'Guindy',
  'kodambakkam':      'Kodambakkam',
  'nungambakkam':     'Nungambakkam',
  'egmore':           'Egmore',
  'royapettah':       'Royapettah',
  'triplicane':       'Triplicane',
  'tondiarpet':       'Tondiarpet',
  'washermanpet':     'Washermanpet',
  'thiruvottiyur':    'Thiruvottiyur',
  'sholinganallur':   'Sholinganallur',
  'perungudi':        'Perungudi',
  'thoraipakkam':     'Thoraipakkam',
  'pallikaranai':     'Pallikaranai',
  'medavakkam':       'Medavakkam',
  'madipakkam':       'Madipakkam',
  'nanganallur':      'Nanganallur',
  'alandur':          'Alandur',
  'saidapet':         'Saidapet',
  'kotturpuram':      'Kotturpuram',
  'besantnagar':      'Besant Nagar',
  'besanthnagar':     'Besant Nagar',

  // Karnataka
  'bangalore':        'Bengaluru',
  'banglore':         'Bengaluru',
  'bangaluru':        'Bengaluru',
  'bengalore':        'Bengaluru',
  'bengaluru':        'Bengaluru',
  'blr':              'Bengaluru',
  'mysore':           'Mysuru',
  'mysuru':           'Mysuru',
  'mangalore':        'Mangaluru',
  'mangaluru':        'Mangaluru',
  'hubli':            'Hubballi',
  'hubballi':         'Hubballi',
  'dharwad':          'Dharwad',
  'belgaum':          'Belagavi',
  'belagavi':         'Belagavi',
  'gulbarga':         'Kalaburagi',
  'kalaburagi':       'Kalaburagi',

  // Andhra / Telangana
  'hyderabad':        'Hyderabad',
  'hydrabad':         'Hyderabad',
  'hyderbad':         'Hyderabad',
  'hyderabd':         'Hyderabad',
  'hyd':              'Hyderabad',
  'secunderabad':     'Secunderabad',
  'vizag':            'Visakhapatnam',
  'visakhapatnam':    'Visakhapatnam',
  'vishakhapatnam':   'Visakhapatnam',
  'vijayawada':       'Vijayawada',
  'warangal':         'Warangal',
  'guntur':           'Guntur',
  'nellore':          'Nellore',
  'tirupati':         'Tirupati',
  'kakinada':         'Kakinada',
  'rajahmundry':      'Rajahmundry',

  // Mumbai / Maharashtra
  'bombay':           'Mumbai',
  'mumbai':           'Mumbai',
  'pune':             'Pune',
  'poona':            'Pune',
  'nagpur':           'Nagpur',
  'nashik':           'Nashik',
  'nasik':            'Nashik',
  'aurangabad':       'Aurangabad',
  'solapur':          'Solapur',
  'thane':            'Thane',
  'navi mumbai':      'Navi Mumbai',
  'navimumbai':       'Navi Mumbai',

  // Delhi / NCR
  'delhi':            'New Delhi',
  'newdelhi':         'New Delhi',
  'ndls':             'New Delhi',
  'gurgaon':          'Gurugram',
  'gurugram':         'Gurugram',
  'noida':            'Noida',
  'faridabad':        'Faridabad',
  'ghaziabad':        'Ghaziabad',
  'meerut':           'Meerut',
  'agra':             'Agra',
  'lucknow':          'Lucknow',
  'kanpur':           'Kanpur',
  'varanasi':         'Varanasi',
  'banaras':          'Varanasi',
  'kashi':            'Varanasi',
  'allahabad':        'Prayagraj',
  'prayagraj':        'Prayagraj',

  // West Bengal
  'calcutta':         'Kolkata',
  'kolkata':          'Kolkata',
  'howrah':           'Howrah',
  'durgapur':         'Durgapur',
  'asansol':          'Asansol',

  // Kerala
  'trivandrum':       'Thiruvananthapuram',
  'thiruvananthapuram': 'Thiruvananthapuram',
  'cochin':           'Kochi',
  'kochi':            'Kochi',
  'ernakulam':        'Ernakulam',
  'calicut':          'Kozhikode',
  'kozhikode':        'Kozhikode',
  'thrissur':         'Thrissur',
  'trichur':          'Thrissur',
  'kollam':           'Kollam',
  'quilon':           'Kollam',
  'palakkad':         'Palakkad',
  'malappuram':       'Malappuram',
  'kannur':           'Kannur',
  'cannanore':        'Kannur',
  'kasaragod':        'Kasaragod',
  'alappuzha':        'Alappuzha',
  'alleppey':         'Alappuzha',
  'kottayam':         'Kottayam',
  'idukki':           'Idukki',
  'pathanamthitta':   'Pathanamthitta',
  'wayanad':          'Wayanad',

  // Rajasthan
  'jaipur':           'Jaipur',
  'jodhpur':          'Jodhpur',
  'udaipur':          'Udaipur',
  'ajmer':            'Ajmer',
  'kota':             'Kota',
  'bikaner':          'Bikaner',

  // Gujarat
  'ahmedabad':        'Ahmedabad',
  'amdavad':          'Ahmedabad',
  'surat':            'Surat',
  'vadodara':         'Vadodara',
  'baroda':           'Vadodara',
  'rajkot':           'Rajkot',
  'bhavnagar':        'Bhavnagar',
  'jamnagar':         'Jamnagar',

  // Punjab / Haryana
  'chandigarh':       'Chandigarh',
  'ludhiana':         'Ludhiana',
  'amritsar':         'Amritsar',
  'jalandhar':        'Jalandhar',
  'patiala':          'Patiala',
  'ambala':           'Ambala',
  'rohtak':           'Rohtak',

  // Odisha
  'bhubaneswar':      'Bhubaneswar',
  'cuttack':          'Cuttack',
  'rourkela':         'Rourkela',

  // Assam / NE
  'guwahati':         'Guwahati',
  'gauhati':          'Guwahati',
  'dibrugarh':        'Dibrugarh',
  'silchar':          'Silchar',

  // Jharkhand / Bihar
  'ranchi':           'Ranchi',
  'jamshedpur':       'Jamshedpur',
  'patna':            'Patna',
  'gaya':             'Gaya',

  // MP / Chhattisgarh
  'bhopal':           'Bhopal',
  'indore':           'Indore',
  'jabalpur':         'Jabalpur',
  'gwalior':          'Gwalior',
  'raipur':           'Raipur',
  'bilaspur':         'Bilaspur',
  'ujjain':           'Ujjain',
  'sagar':            'Sagar',
  'ratlam':           'Ratlam',
  'satna':            'Satna',
  'durg':             'Durg',
  'bhilai':           'Bhilai Nagar',
  'bhilainagar':      'Bhilai Nagar',
  'korba':            'Korba',

  // Rajasthan (additional)
  'bhilwara':         'Bhilwara',
  'alwar':            'Alwar',
  'bharatpur':        'Bharatpur',
  'sikar':            'Sikar',
  'barmer':           'Barmer',
  'nagaur':           'Nagaur',
  'tonk':             'Tonk',
  'pali':             'Pali',

  // Uttar Pradesh (additional)
  'firozabad':        'Firozabad',
  'saharanpur':       'Saharanpur',
  'jhansi':           'Jhansi',
  'aligarh':          'Aligarh',
  'moradabad':        'Moradabad',
  'amroha':           'Amroha',
  'shahjahanpur':     'Shahjahanpur',
  'mathura':          'Mathura',
  'vrindavan':        'Mathura',
  'mirzapur':         'Mirzapur',

  // Maharashtra (additional)
  'amravati':         'Amravati',
  'akola':            'Akola',
  'latur':            'Latur',
  'dhule':            'Dhule',
  'nanded':           'Nanded-Waghala',
  'nandedwaghala':    'Nanded-Waghala',
  'malegaon':         'Malegaon',
  'sangli':           'Sangli',
  'bhiwandi':         'Bhiwandi',
  'kalyan':           'Kalyan-Dombivali',
  'dombivali':        'Kalyan-Dombivali',
  'kalyandombivali':  'Kalyan-Dombivali',
  'vasaivirar':       'Vasai-Virar',
  'mirabhayandar':    'Mira-Bhayandar',
  'parbhani':         'Parbhani',
  'wardha':           'Wardha',
  'yavatmal':         'Yavatmal',
  'osmanabad':        'Osmanabad',
  'nandurbar':        'Nandurbar',
  'satara':           'Satara',
  'ratnagiri':        'Ratnagiri',
  'panvel':           'Panvel',
  'palghar':          'Palghar',
  'lonavla':          'Lonavla',
  'shirdi':           'Shirdi',
  'kolhapur':         'Kolhapur',
  'ichalkaranji':     'Ichalkaranji',
  'ahmednagar':       'Ahmednagar',

  // Karnataka (additional)
  'davanagere':       'Davanagere',
  'davangere':        'Davanagere',
  'ballari':          'Ballari',
  'bellary':          'Ballari',
  'tumkur':           'Tumkur',
  'tumakuru':         'Tumkur',
  'shivamogga':       'Shivamogga',
  'shimoga':          'Shivamogga',

  // Andhra Pradesh (additional)
  'kurnool':          'Kurnool',
  'anantapur':        'Anantapur',
  'vizianagaram':     'Vizianagaram',
  'kadapa':           'Kadapa',
  'cuddapah':         'Kadapa',
  'eluru':            'Eluru',

  // Telangana (additional)
  'karimnagar':       'Karimnagar',
  'nizamabad':        'Nizamabad',
  'ramagundam':       'Ramagundam',
  'khammam':          'Khammam',

  // Bihar (additional)
  'muzaffarpur':      'Muzaffarpur',
  'bhagalpur':        'Bhagalpur',
  'darbhanga':        'Darbhanga',

  // West Bengal (additional)
  'siliguri':         'Siliguri',
  'kharagpur':        'Kharagpur',

  // Haryana (additional)
  'hisar':            'Hisar',
  'panipat':          'Panipat',
  'karnal':           'Karnal',
  'sonipat':          'Sonipat',
  'yamunanagar':      'Yamunanagar',
  'rewari':           'Rewari',
  'panchkula':        'Panchkula',

  // Punjab (additional)
  'bathinda':         'Bathinda',
  'bhatinda':         'Bathinda',
  'pathankot':        'Pathankot',
  'hoshiarpur':       'Hoshiarpur',
  'mohali':           'Mohali',
  'zirakpur':         'Zirakpur',

  // Gujarat (additional)
  'gandhinagar':      'Gandhinagar',
  'anand':            'Anand',
  'nadiad':           'Nadiad',
  'bharuch':          'Bharuch',
  'broach':           'Bharuch',
  'navsari':          'Navsari',
  'vapi':             'Vapi',
  'mahesana':         'Mahesana',
  'mehsana':          'Mahesana',
  'morvi':            'Morvi',
  'bhuj':             'Bhuj',
  'porbandar':        'Porbandar',

  // Uttarakhand
  'dehradun':         'Dehradun',
  'dehra dun':        'Dehradun',
  'haridwar':         'Hardwar',
  'hardwar':          'Hardwar',
  'rishikesh':        'Rishikesh',
  'haldwani':         'Haldwani',
  'nainital':         'Nainital',
  'mussoorie':        'Mussoorie',

  // Himachal Pradesh
  'shimla':           'Shimla',
  'simla':            'Shimla',
  'kullu':            'Kullu',
  'kulu':             'Kullu',
  'manali':           'Manali',

  // Jammu & Kashmir
  'jammu':            'Jammu',
  'srinagar':         'Srinagar',

  // Odisha (additional)
  'brahmapur':        'Brahmapur',
  'berhampur':        'Brahmapur',
  'sambalpur':        'Sambalpur',
  'puri':             'Puri',

  // Assam (additional)
  'jorhat':           'Jorhat',
  'tezpur':           'Tezpur',
  'nagaon':           'Nagaon',
  'dispur':           'Dispur',

  // NE States
  'kohima':           'Kohima',
  'dimapur':          'Dimapur',
  'shillong':         'Shillong',
  'imphal':           'Imphal',
  'agartala':         'Agartala',
  'aizawl':           'Aizawl',

  // Goa
  'panaji':           'Panaji',
  'panjim':           'Panaji',
  'margao':           'Margao',
  'madgaon':          'Margao',
}
